<?php

namespace app\models;

use Yii;
use \app\core\models\Model;
use \yii\behaviors\TimestampBehavior;
/**
 * This is the model class for table "{{%api_month_cron_setting}}".
 *
 * @property string $id
 * @property string $time
 * @property string $status
 */
class ApiMonthCronSetting extends Model
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%api_month_cron_setting}}';
    }




    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['time', 'status'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'time' => 'Time',
            'status' => 'Status',
        ];
    }
    public function beforeValidate()
    {
        list($year,$month) = explode('-',$this->time);

        $this->time = mktime(0,0,0,$month,1,$year);
        $this->status = $this->time;
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

}
